[firebase]
type = "service_account"
project_id = "crypto-e9605"
private_key_id = "d8fa3357c1b527781461516f2cd1b338a78e939c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCHciWJnvHhrdDW
fO26k7iOZ3ybztHGJpQQkj9mzj33pPBc/YS2Xrwr2quMn84d2siUGZZFzTADhNOs
weITNOMAxK7xCYhSr+yFY0PY2ghWEGNr43uGG/k5nSdox9OUue6gQW4Vy1JhUbIK
dlmmmfOYaYuzfksvzqjt2DXumrQXXBt5Fu+HDMyxOEahHjrD/XKTC3idpqgDhcFQ
/DfnESLDT1e4x5/lWAU8licFlKuYleyFb306zNAtcN7BB3Ga2GgLxZFMGaxYEnk4
cfLMOzXKqy0UdXRwXiI54XusdxouTxRPKirnTOIQXl1aPg/8oPFdmGoShTCAtSXe
+fgAeX4vAgMBAAECggEALmccViA2pQcL/5ewSFX4ig0JQ0XhV137Jww7nWh2EWQY
Fvuh3mrpU6roT9al4lOEmTyE36gS1XnJnSuVXNgnFynK93g5FH8B7Jbb9SyJY5bc
wOcf+AuYYDUnfb3MDm1+w7d21A+iywWWlgAC6dFfg61RN67CaoAGHuoOXA7zOPcN
OTHDTvqu0/30eu6aOUQOzVvRydQM/IvWPg9IzhkMptutHzuFzaTE2zRpEx1GCPTn
Hxyk00bM9pbyZrDIqlb7UqFubIiCcbQJWETJAdOUHTUPkxWDa7/+ydlECyMVtaRT
xVxdEPEN+lLm3GTLuZ00ct5A08dW06Qjx3cYj/NXzQKBgQC6yspBme7l6gbR4MRo
wV3iiQRklP7retECUqRBFXosMYpr4VLXjyLgVUo8Z+NP7qTwjfHOlxIKSgmA0I83
cEy3u+jlXGWR1WyzsCteZUYuLOhVSL2bFAv4rqxiOspru5zRI6jU6buxDQJDK7aB
75WJOTOVtEpWF1kEfnj36gDXXQKBgQC5oSujBfecTg/7BVTDCRFdHR/V8Apb3jdZ
19ywW0wUJCL/hbKUhlzLSQe4BR7mTU7H2UdaZGhxdu14Sws3PX5tMCC0sYBikU4K
H1NuoGeFp5w9IMfYhnl7KmqgaKjwC8V8pP7/GtziMBW70RKNr+dWGoX0lWm2rDWU
5jhzN6hO+wKBgHrXusQB1BboHawRQZoS8Qd2TKlJQ4zhrGr2pocW9M3zlrDz8mNJ
Awq9jKDFQbzjmR2KfCf9OiQCJNXOUyGGfS2oKrYMWc/aqC5UAXGG8OyVJAZSXD+M
o4LcfQns2AqZy7vO082SGZmKkJ5UNSamxZUFRWOCuhB8MlK+ShfgkMURAoGACFJb
XHGWCiHNwZkZlazAZIY7uSGLtVae8J4mvJk7LeP41a+us83aNxrNB8ji+7wXfgoV
ks3RiNSmDLCAjjdphYeUz8TtVn3hG78PxHPYcDt1W6AulVxh8c2S/iHzAN/mOJJF
BDa2FEXHk6XpyQRLwKZrvu070f6iYEx512B1YSUCgYBdgwmN4/zB9PVJvmfGOZZI
Qu3/djPmIYpNxCqtCde3HtexHy4CgV7xBEafTZ2D7HvYndKwwIIqx2lzhaytWYol
YafXMpWPPy4f5IAGjCVim4kMNhecY5wgUkSYAUwnl88Sp6X6+dlCNKUx5BmIn0yN
HdAzehARpN38QVLAjtMIUQ==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@crypto-e9605.iam.gserviceaccount.com"
client_id = "107778011069772761329"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40crypto-e9605.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
